services:
  gitlab:
    image: gitlab/gitlab-ce:18.3.5-ce.0
    container_name: gitlab
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitlab.rule=Host(`gitlab.portal.poc`)
      - traefik.http.routers.gitlab.service=gitlab
      - traefik.http.services.gitlab.loadbalancer.server.port=80
    restart: always
    hostname: 'gitlab.portal.poc'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.portal.poc'
        letsencrypt['enable'] = false

        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        nginx['proxy_set_headers'] = {
          "X-Forwarded-Proto" => "https",
          "X-Forwarder-Ssl" => "on"
        }

        gitlab_rails['gitlab_shell_ssh_port'] = 2424
    ports:
#      - '80:80'
#      - '443:443'
      - '2424:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'
